// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type PasswordStore struct {
	ID        string
	Domain    string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
