// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const findPasswordUsingDomain = `-- name: FindPasswordUsingDomain :one
SELECT id, domain, password, created_at, updated_at FROM password_store WHERE domain = ?
`

func (q *Queries) FindPasswordUsingDomain(ctx context.Context, domain string) (PasswordStore, error) {
	row := q.db.QueryRowContext(ctx, findPasswordUsingDomain, domain)
	var i PasswordStore
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPasswords = `-- name: GetAllPasswords :many
SELECT id, domain, password, created_at, updated_at FROM password_store
`

func (q *Queries) GetAllPasswords(ctx context.Context) ([]PasswordStore, error) {
	rows, err := q.db.QueryContext(ctx, getAllPasswords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasswordStore
	for rows.Next() {
		var i PasswordStore
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIntoPasswordStore = `-- name: InsertIntoPasswordStore :exec
INSERT INTO password_store (id, domain, password)
VALUES (?, ?, ?)
`

type InsertIntoPasswordStoreParams struct {
	ID       string
	Domain   string
	Password string
}

func (q *Queries) InsertIntoPasswordStore(ctx context.Context, arg InsertIntoPasswordStoreParams) error {
	_, err := q.db.ExecContext(ctx, insertIntoPasswordStore, arg.ID, arg.Domain, arg.Password)
	return err
}
